### PR TITLE
Test CODEOWNERS

### PR DESCRIPTION
**Pull request by thewilkybarkid**
Following #17.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
Seemed to work. Means @stephenwf will now have write access. (Was hoping we could give people review-only access, so more reviewers than mergers.)

**Comment by thewilkybarkid** [comment]
Reviewers list shows the group, thought it showed the individuals (having looked at PRs in https://github.com/doctrine/coding-standard).

**Comment by giorgiosironi** [comment]
I did receive this email
```
@thewilkybarkid requested review from @libero/php-reviewers on: libero/php-coding-standard#18 Test CODEOWNERS as a code owner.
```
which indicates notifying each team members works. Assuming it was automated as expected.

**Comment by stephenwf** [comment]
Hmm, maybe reviewers could be listed individually, and then @libero/php-reviewers could contain those with write access. Or would that also not work?

**Comment by giorgiosironi** [comment]
After adding my review, list change to just me. @stephenwf I guess if you add your own review, it will then list also you as the original assignment to the team has already been lost.

**Comment by giorgiosironi** [comment]
(I assume we are working on `0.1` to test this behavior, as version branches should depart from master normally)

**Comment by thewilkybarkid** [comment]
@stephenwf:

> The people you choose as code owners must have write permissions for the repository.

Oh well, enjoy your new powers! (Not too much 😛)

@giorgiosironi we'll need to include the file on all branches, will merge `0.1` into `master`.

**Comment by giorgiosironi** [comment]
For the record:

**Pull request closed without merging**
